### ISSUE TITLE
don't open web-page

### ISSUE THREAD

**Issue by DEaDEGORkA** [xaviviro/refacer#15]
after installing i tryed to open link http://127.0.0.1:7680 in web-brouser. it shows "Unable to access the site". OC WIN10

**Comment by suphamster** [comment]
I had same problem, it was fixed when I've closed command line window (in my case it was "Anaconda Promt") and started python script again it run fine after that. Also port number changed from 7680 to 7681.
Btw tool works fine on Python 3.9.16 for me.

**Comment by DEaDEGORkA** [comment]
my port dont change

**Comment by DEaDEGORkA** [comment]
it should be preinstalled Visual studio?

**Comment by suphamster** [comment]
I dunno since I'm not developer about Visual Studio but I had it installed. But I think web page should work without it but to install dependencies u could need it.
U can look here https://disk.yandex.ru/d/OcHdF2kzO6YdjQ there are instructions, portable versions, etc from devs. Thats all I can help. Try restarting PC if cmd restart not helped.

**Comment by xaviviro** [comment]
If after installing you've tried to launch the app with `python app.py` and it's not working, check your Windows firewall. And if the issue is related to the port, you can now change it thanks to @fAIseh00d commit here: https://github.com/xaviviro/refacer/commit/0e79a8a5703443403e1f52c735a52c5c5481fa6c. You can change the port by running `python app.py —server_port 12345`.
